---
title: "Parallel"
format: html
---

---
title: "Practical One"
format: html
---

## Packages

```{r}
library(foreach)
library(doParallel)
library(MASS)
library(boot)
library(iterators)
library(parallel)
library(microbenchmark)

```

## Question 1

```{r}
numCores = detectCores() -1
cl <- makeCluster(numCores)
registerDoParallel(numCores)
n <- 100

results <- foreach(i = 1:n, .combine = rbind, .packages = "stats") %dopar% {
  sample_d <- rexp(100, rate = 1)
  mean_s <- mean(sample_d)
  var_s <- var(sample_d)
  c(mean_s, var_s)
}
stopCluster(cl)

result_df <- as.data.frame(results)
colnames(result_df) <- c("Mean", "Variance")
head(result_df)

```

## Question 2

```{r}
temp_summary = airquality_data %>% summarise(
  mean_temp = mean(Temp, na.rm = TRUE),
  sd_temp = sd(Temp, na.rm = TRUE),
  min_temp = min(Temp, na.rm = TRUE),
  max_temp = max(Temp, na.rm = TRUE),
)

ozone_summary = airquality_data %>% summarise(
  mean_ozone = mean(Ozone, na.rm = TRUE),
  sd_ozone = sd(Ozone, na.rm = TRUE),
  min_ozone = min(Ozone, na.rm = TRUE),
  max_ozone = max(Ozone, na.rm = TRUE),
)

temp_summary
ozone_summary

```

## Question 3

```{r}
speed_matrix = matrix(cbind(1, cars_data$speed), ncol=2)
Y = cars_data$dist

beta_hat = solve(t(speed_matrix) %*% speed_matrix) %*% t(speed_matrix) %*% Y
beta_hat
```

## Question 4

```{r,}
lm_model <- lm(dist ~ speed, data = cars_data)
summary(lm_model)$coefficients
```